import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url), sharp=require('sharp'), root=process.cwd();
const data=JSON.parse(fs.readFileSync(path.join(root,'playlist-data.json'),'utf8'));
const covers=fs.readdirSync(path.join(root,'covers')).filter(f=>/^\d{2}-.*\.jpg$/i.test(f)&&!f.startsWith('00-')).sort();
const W=10000,H=7600,CW=900,CH=300,GAP=30;
const colors={chill:'#53dfd0',energetic:'#ffb348',pop:'#ff6f91',jamaican:'#83dc62',raps:'#eec84e',edm:'#55a9ff',dnb:'#9b8cff',weird:'#de74ee','guitars and such':'#62d29a',psy:'#c6ee4e','4-on-4':'#ff9b3e',hard:'#ff5752',traditional:'#d2a06a'};
const regions={energetic:{x:100,y:280,w:2500,h:1450,cols:2},chill:{x:2750,y:280,w:3050,h:3320,cols:3},pop:{x:6000,y:380,w:2900,h:3320,cols:3},edm:{x:1000,y:1850,w:2700,h:1900,cols:2},dnb:{x:50,y:2300,w:1900,h:1200,cols:1},jamaican:{x:100,y:3900,w:1100,h:850,cols:1},raps:{x:1350,y:4050,w:1100,h:1150,cols:1},psy:{x:3800,y:2700,w:1100,h:1600,cols:1},'4-on-4':{x:3600,y:3200,w:3500,h:2350,cols:2,startY:1120},hard:{x:6200,y:3700,w:2200,h:1950,cols:1,startY:820},weird:{x:7450,y:4000,w:2250,h:1800,cols:2},'guitars and such':{x:100,y:5450,w:2050,h:1800,cols:2},traditional:{x:8200,y:5950,w:1500,h:1500,cols:1}};
const sharedPos={'glitter, distortion and autotune':[7925,5400],'welcome, alien overlords!':[1475,2600],'bruh, are we the aliens?':[1475,2940],"let's cry naked on the subway":[3225,2150],'ride the dragon, aummmmm':[4350,3950],'melt away into the universe':[4300,3000],'oh my techno goodness':[6650,4100],'come down at the afterparty':[5350,3400],'ex & estrogen':[6550,3450]};
const esc=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const cats=p=>p.Category.split(',').map(s=>s.trim());
function wrap(text,max,maxLines){const out=[];let line='';for(const word of String(text).split(/\s+/)){const next=line?`${line} ${word}`:word;if(next.length<=max||!line)line=next;else{out.push(line);line=word}}if(line)out.push(line);if(out.length>maxLines){const x=out.slice(0,maxLines);x[maxLines-1]=x[maxLines-1].replace(/[.,;:]?$/,'…');return x}return out}
const cover=i=>`data:image/jpeg;base64,${fs.readFileSync(path.join(root,'covers',covers[i])).toString('base64')}`;
const lines=(ls,x,y,cl,lh)=>`<text x="${x}" y="${y}" class="${cl}">${ls.map((l,i)=>`<tspan x="${x}" dy="${i?lh:0}">${esc(l)}</tspan>`).join('')}</text>`;
function card(p,x,y,i,shared=false){const id=`card-${String(i+1).padStart(2,'0')}`,cs=cats(p),title=wrap(p.Name.toUpperCase(),31,2),desc=wrap(p.Description,47,5),genres=wrap(p.Genres,47,3),tx=x+300,titleY=y+48,descY=titleY+(title.length-1)*30+39,genresY=descY+(desc.length-1)*21+35,border=shared?`url(#mix-${slug(p.Name)})`:colors[cs[0]];return `<a href="${esc(p.URL)}" target="_blank"><g id="${id}" class="playlist-card" data-category="${esc(p.Category)}" data-length-level="${esc(p['Length category (1–5)'])}"><title>${esc(p.Name)} — ${esc(p.Description)}</title><rect x="${x}" y="${y}" width="${CW}" height="${CH}" rx="12" fill="#10161d" fill-opacity=".97" stroke="${border}" stroke-width="${shared?7:3}" filter="url(#shadow)"/><clipPath id="clip-${id}"><rect x="${x+20}" y="${y+20}" width="260" height="260" rx="8"/></clipPath><image href="${cover(i)}" x="${x+20}" y="${y+20}" width="260" height="260" preserveAspectRatio="xMidYMid slice" clip-path="url(#clip-${id})"/>${lines(title,tx,titleY,'card-title',30)}${lines(desc,tx,descY,'card-desc',21)}${lines(genres,tx,genresY,'card-genres',21)}<g transform="translate(${x+CW-28-cs.length*24} ${y+22})">${cs.map((c,j)=>`<rect x="${j*24}" width="16" height="7" rx="3" fill="${colors[c]}"/>`).join('')}</g></g></a>`}
const singles=Object.fromEntries(Object.keys(regions).map(k=>[k,[]]));data.forEach((p,i)=>{const cs=cats(p);if(cs.length===1)singles[cs[0]].push({p,i})});
function roundedPath(points,radius=72){const near=(v,o)=>{const dx=o[0]-v[0],dy=o[1]-v[1],d=Math.hypot(dx,dy)||1,t=Math.min(radius,d*.42)/d;return[v[0]+dx*t,v[1]+dy*t]};const parts=[];for(let i=0;i<points.length;i++){const v=points[i],prev=points[(i-1+points.length)%points.length],next=points[(i+1)%points.length],entry=near(v,prev),exit=near(v,next);if(i===0)parts.push(`M ${entry[0]} ${entry[1]}`);else parts.push(`L ${entry[0]} ${entry[1]}`);parts.push(`Q ${v[0]} ${v[1]} ${exit[0]} ${exit[1]}`)}return parts.join(' ')+' Z'}
function territoryPath(r){const{x,y,w,h}=r;return roundedPath([[x+80,y],[x+w*.54,y],[x+w*.54,y-26],[x+w-110,y-26],[x+w,y+84],[x+w,y+h*.36],[x+w+34,y+h*.36],[x+w+34,y+h*.64],[x+w,y+h*.64],[x+w,y+h-100],[x+w-100,y+h],[x+w*.61,y+h],[x+w*.61,y+h+24],[x+90,y+h+24],[x,y+h-82],[x,y+h*.66],[x-28,y+h*.66],[x-28,y+h*.41],[x,y+h*.41],[x,y+82]],76)}
function region(cat){const r=regions[cat],c=colors[cat],label=cat.toUpperCase();return `<g id="region-${slug(cat)}" class="category-region" data-category="${esc(cat)}"><path d="${territoryPath(r)}" fill="${c}" fill-opacity=".075" stroke="${c}" stroke-opacity=".78" stroke-width="5"/><rect x="${r.x+28}" y="${r.y+28}" width="${Math.max(250,label.length*25+80)}" height="64" rx="18" fill="#081016" stroke="${c}" stroke-width="3"/><text x="${r.x+58}" y="${r.y+70}" class="category" fill="${c}">${esc(label)}</text></g>`}
const center=cat=>{const r=regions[cat];return[r.x+r.w/2,r.y+r.h/2]};
function pads(){return ''}
const shared=data.map((p,i)=>({p,i})).filter(({p})=>cats(p).length>1);
const gradients=shared.map(({p})=>{const cs=cats(p);return `<linearGradient id="mix-${slug(p.Name)}"><stop stop-color="${colors[cs[0]]}"/><stop offset="1" stop-color="${colors[cs[1]]}"/></linearGradient>`}).join('');
const singleCards=Object.entries(singles).flatMap(([cat,list])=>{const r=regions[cat],startY=r.startY??120;return list.map(({p,i},n)=>card(p,r.x+38+(n%r.cols)*(CW+GAP),r.y+startY+Math.floor(n/r.cols)*(CH+GAP),i))}).join('');
const sharedCards=shared.map(({p,i})=>{const[cx,cy]=sharedPos[p.Name];return card(p,cx-CW/2,cy-CH/2,i,true)}).join('');
const bg=fs.existsSync(path.join(root,'playlist-map-background.png'))?fs.readFileSync(path.join(root,'playlist-map-background.png')).toString('base64'):'';
const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" role="img" aria-labelledby="map-title map-desc"><title id="map-title">64 Playlists — A Listening Map</title><desc id="map-desc">Interactive-ready category map with playlist covers, descriptions, and genres. Shared cards sit entirely inside overlapping category areas.</desc><defs>${gradients}<filter id="shadow" x="-15%" y="-20%" width="130%" height="150%"><feDropShadow dx="0" dy="10" stdDeviation="15" flood-color="#000" flood-opacity=".55"/></filter><style>.headline{font:800 72px 'Segoe UI',Arial,sans-serif;fill:#f4f7fb;letter-spacing:2px}.subhead{font:400 26px 'Segoe UI',Arial,sans-serif;fill:#aeb9c6}.category{font:800 27px 'Segoe UI',Arial,sans-serif;letter-spacing:4px}.card-title{font:800 25px 'Segoe UI',Arial,sans-serif;fill:#fff;letter-spacing:.7px}.card-desc{font:400 17px 'Segoe UI',Arial,sans-serif;fill:#b8c2cc}.card-genres{font:750 17px 'Arial Narrow','Segoe UI',Arial,sans-serif;fill:#f0f3f6;letter-spacing:.25px}.playlist-card{cursor:pointer}.playlist-card:hover rect:first-of-type{fill:#17212b}</style></defs><rect width="${W}" height="${H}" fill="#070a0e"/>${bg?`<image href="data:image/png;base64,${bg}" width="${W}" height="${H}" preserveAspectRatio="xMidYMid slice" opacity=".10"/>`:''}<rect width="${W}" height="${H}" fill="#070a0e" fill-opacity=".55"/><text x="110" y="105" class="headline">64 PLAYLISTS — A LISTENING MAP</text><text x="115" y="154" class="subhead">Category territories are rectangular; shared playlists live fully inside both colored overlap zones.</text>${Object.keys(regions).map(region).join('')}${shared.map(({p})=>pads(p)).join('')}${singleCards}${sharedCards}<g transform="translate(6720 5315)"><rect width="1360" height="140" rx="12" fill="#10161d" stroke="#34404c" stroke-width="3"/><circle cx="52" cy="52" r="12" fill="#53dfd0"/><circle cx="82" cy="52" r="12" fill="#ff9b3e"/><text x="112" y="61" class="card-genres">TWO-COLOR BORDER = SHARED PLAYLIST</text><text x="52" y="104" class="card-desc">Every card links to its Spotify playlist in the SVG version.</text></g></svg>`;
const finalSvg=svg.replace('Category territories are rectangular;','Category territories overlap directly;').replace('translate(6720 5315)','translate(8450 180)');
fs.writeFileSync(path.join(root,'playlist-bubble-map.svg'),finalSvg);
const rasterSvg=finalSvg.replace(`width="${W}" height="${H}"`,`width="4100" height="3116"`);
await sharp(Buffer.from(rasterSvg)).png({compressionLevel:9,adaptiveFiltering:true}).toFile(path.join(root,'playlist-bubble-map.png'));
await sharp(Buffer.from(rasterSvg)).resize({width:2400}).jpeg({quality:88,mozjpeg:true}).toFile(path.join(root,'playlist-bubble-map-preview.jpg'));
console.log(`Rendered ${data.length} cards; ${shared.length} shared cards.`);
